name: Build Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt install pandoc
        python -m pip install --upgrade pip
        pip install -U Sphinx
        pip install furo
    - name: Build sphinx documentation
      run: |
        make html
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
